language: c
compiler:
    - gcc
    - clang
script: make
notifications:
    email:
        recipients:
            - alexsimonjones@gmail.com
        on_sucess: [never]
        on_failure: [always] # default: always
